# Generated by Django 3.1.7 on 2021-11-26 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_grade_level', models.CharField(choices=[('1H', '1(H)'), ('1L', '1(L)'), ('2H', '2(H)'), ('2L', '2(L)'), ('3H', '3(H)'), ('3L', '3(L)'), ('4H', '4(H)'), ('4L', '4(L)'), ('5H', '5(H)'), ('5L', '5(L)'), ('6H', '6(H)'), ('6L', '6(L)'), ('7H', '7(H)'), ('7L', '7(L)'), ('8H', '8(H)'), ('8L', '8(L)'), ('9H', '9(H)'), ('9L', '9(L)'), ('10H', '10(H)'), ('10L', '10(L)'), ('11H', '11(H)'), ('11L', '11(L)'), ('12H', '12(H)'), ('12L', '12(L)'), ('13H', '13(H)'), ('13L', '13(L)'), ('14H', '14(H)'), ('14L', '14(L)'), ('15H', '15(H)'), ('15L', '15(L)'), ('16H', '16(H)'), ('16L', '16(L)'), ('17H', '17(H)'), ('17L', '17(L)'), ('18H', '18(H)'), ('18L', '18(L)'), ('19H', '19(H)'), ('19L', '19(L)'), ('20H', '20(H)'), ('20L', '20(L)'), ('21H', '21(H)'), ('21L', '21(L)'), ('22H', '22(H)'), ('22L', '22(L)'), ('23H', '23(H)'), ('23L', '23(L)'), ('24H', '24(H)'), ('24L', '24(L)'), ('25H', '25(H)'), ('25L', '24(L)')], max_length=3)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=500)),
                ('aliase', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('inst_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='fairwages.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=1000)),
                ('staff_id', models.IntegerField(null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_n', to='fairwages.institution')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_grade_level', to='fairwages.grade')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='fairwages.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='GradeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=200, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_staf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='fairwages.staff')),
                ('job_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='fairwages.jobrole')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_inst', to='fairwages.institution')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage', to='fairwages.grade')),
                ('ss_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_level', to='fairwages.grade')),
                ('staff_fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fname', to='fairwages.staff')),
            ],
        ),
    ]
