# Generated by Django 3.1.7 on 2021-10-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=1000)),
                ('aliase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('inst_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='fairwages.institution')),
            ],
        ),
        migrations.CreateModel(
            name='gradeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_grade', models.IntegerField()),
                ('submission_date', models.DateTimeField()),
                ('level', models.CharField(choices=[('H', 'High'), ('L', 'Low')], max_length=1)),
                ('creator', models.CharField(max_length=100)),
                ('wage', models.FloatField()),
                ('job_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='fairwages.jobrole')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_inst', to='fairwages.institution')),
            ],
        ),
    ]
